/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.tabelas.Pedido;
import br.edu.ifnmg.tabelas.Transportadora;
import br.edu.ifnmg.tabelasDao.PedidoDao;
import br.edu.ifnmg.tabelasDao.TransportadoraDao;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Filip
 */
public class CadastroPedido extends javax.swing.JInternalFrame {

    
    private List<Transportadora> todasTransportadoras;
    private Long codVendedor;
    private Pedido pedido;
//    private List<Autor> todosAutores;
    
    /**
     * Creates new form CadastroPedido
     */
    public CadastroPedido(){
        
    }
    
    
    public CadastroPedido(Long codigoVendedor) {
        initComponents();
        
        this.codVendedor = codigoVendedor;
        
        // Preenchimento de editoras para seleção no cadastro
        todasTransportadoras = new TransportadoraDao().localizarTodos();
        DefaultComboBoxModel<Transportadora> comboBoxModel
                = new DefaultComboBoxModel<>();
        comboBoxModel.addAll(todasTransportadoras);
        cboCodigoTransportadora.setModel(comboBoxModel);

//        // Preenchimento de autores para seleção no cadastro
//        todosAutores = new AutorDao().localizarTodos();
//        DefaultListModel<Autor> listModel = new DefaultListModel<>();
//        listModel.addAll(todosAutores);
//        lstAutor.setModel(listModel);        
        
    }
    
    public CadastroPedido(Pedido pedido) {
        this();

        this.pedido = pedido;

        cboCodigoTransportadora.getModel().setSelectedItem(
                pedido.getCodigo_transportadora());
        
        
    }
    
    
    
    

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboCodigoTransportadora = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataEnvio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataRecebimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContaCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroCartaoCredito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoConfirmacao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtImposto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEnderecoFatura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEnderecoEntrega = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pedido");

        jLabel1.setText("Codigo Transportadora:");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Data pedido:");

        jLabel4.setText("Data envio:");

        txtDataEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEnvioActionPerformed(evt);
            }
        });

        jLabel5.setText("Data recebimento:");

        txtDataRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataRecebimentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo cliente:");

        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Conta cliente:");

        txtContaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContaClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero cartão crédito:");

        jLabel9.setText("Código confirmação:");

        jLabel10.setText("Imposto:");

        jLabel11.setText("Endereço fatura:");

        jLabel12.setText("Endereço entrega:");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)))
                        .addComponent(jLabel8))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCodigo)
                        .addComponent(txtDataPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtDataEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtDataRecebimento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtCodigoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtContaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtNumeroCartaoCredito)
                        .addComponent(txtCodigoConfirmacao, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtImposto)
                        .addComponent(txtEnderecoFatura)
                        .addComponent(txtEnderecoEntrega, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(cboCodigoTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnInserir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigoConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnderecoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnderecoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCodigoTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEnvioActionPerformed

    private void txtDataRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataRecebimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataRecebimentoActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void txtContaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContaClienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        Pedido pedido = new Pedido();
        pedido.setCodigo(Long.parseLong(txtCodigo.getText()));
        pedido.setData_pedido(txtDataPedido.getText());
        pedido.setData_envio(txtDataEnvio.getText());
        pedido.setData_recebimento(txtDataRecebimento.getText());
        pedido.setCodigo_cliente(Long.parseLong(txtCodigoCliente.getText()));
        pedido.setConta_cliente(txtContaCliente.getText());
        pedido.setNumero_cartao_credito(Long.parseLong(txtNumeroCartaoCredito.getText()));
        pedido.setCodigo_confirmacao(txtCodigoConfirmacao.getText());
        
        pedido.setCodigo_vendedor(codVendedor);
        
        pedido.setImposto(Double.parseDouble(txtImposto.getText()));
        pedido.setEndereco_fatura(Long.parseLong(txtEnderecoFatura.getText()));
        pedido.setEndereco_entrega(Long.parseLong(txtEnderecoEntrega.getText()));
        
        Transportadora transportadora = (Transportadora) cboCodigoTransportadora.getSelectedItem();
        pedido.setCodigo_transportadora(transportadora.getCodigo());
        
        
        PedidoDao pedidoDao = new PedidoDao();
        pedidoDao.salvar(pedido);
        
        
        
        
    }//GEN-LAST:event_btnInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<Transportadora> cboCodigoTransportadora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoConfirmacao;
    private javax.swing.JTextField txtContaCliente;
    private javax.swing.JTextField txtDataEnvio;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtDataRecebimento;
    private javax.swing.JTextField txtEnderecoEntrega;
    private javax.swing.JTextField txtEnderecoFatura;
    private javax.swing.JTextField txtImposto;
    private javax.swing.JTextField txtNumeroCartaoCredito;
    // End of variables declaration//GEN-END:variables
}
