/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.tabelas.Vendedor;

/**
 *
 * @author Filip
 */
public class InterfaceVendedor extends javax.swing.JFrame {

   
    private Vendedor vendedorAutenticado;
    private Long codigoVendedor;
    
    
    public InterfaceVendedor(Vendedor vendedorAutenticado, Long codigoVendedor) {
        this.vendedorAutenticado = vendedorAutenticado;
        initComponents();
        
        this.codigoVendedor = codigoVendedor;
        
        
        // Centralização da janela
        setLocationRelativeTo(null);
    }
    
    

    public InterfaceVendedor() {
        initComponents();
        // Centralização da janela
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskInterfaceVendedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPedidos = new javax.swing.JMenu();
        mnuListarPedidos = new javax.swing.JMenuItem();
        mnuInserirPedido = new javax.swing.JMenuItem();
        mnuAtualizarPedido = new javax.swing.JMenuItem();
        mnuRemoverPedido = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskInterfaceVendedorLayout = new javax.swing.GroupLayout(dskInterfaceVendedor);
        dskInterfaceVendedor.setLayout(dskInterfaceVendedorLayout);
        dskInterfaceVendedorLayout.setHorizontalGroup(
            dskInterfaceVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        dskInterfaceVendedorLayout.setVerticalGroup(
            dskInterfaceVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        mnuPedidos.setText("Pedidos");

        mnuListarPedidos.setText("Listar");
        mnuPedidos.add(mnuListarPedidos);

        mnuInserirPedido.setText("Inserir");
        mnuInserirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInserirPedidoActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuInserirPedido);

        mnuAtualizarPedido.setText("Atualizar");
        mnuPedidos.add(mnuAtualizarPedido);

        mnuRemoverPedido.setText("Remover");
        mnuRemoverPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoverPedidoActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuRemoverPedido);

        jMenu1.add(mnuPedidos);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskInterfaceVendedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskInterfaceVendedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        Login telaLogin = new Login();
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuInserirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInserirPedidoActionPerformed
        CadastroPedido cadPedido = new CadastroPedido(codigoVendedor);
        cadPedido.setVisible(true);
        dskInterfaceVendedor.add(cadPedido);
        
    }//GEN-LAST:event_mnuInserirPedidoActionPerformed

    private void mnuRemoverPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoverPedidoActionPerformed
        RemoverPedido rmvPedido = new RemoverPedido(codigoVendedor);
        rmvPedido.setVisible(true);
        dskInterfaceVendedor.add(rmvPedido);
        
    }//GEN-LAST:event_mnuRemoverPedidoActionPerformed
    private void mnuListarPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        ListarPedido lista = new ListarPedido();
        lista.setVisible(true);
        dskInterfaceVendedor.add(lista);
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskInterfaceVendedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAtualizarPedido;
    private javax.swing.JMenuItem mnuInserirPedido;
    private javax.swing.JMenuItem mnuListarPedidos;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenuItem mnuRemoverPedido;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
