/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.bd.ConexaoBd;


/**
 *
 * @author Filip
 */
public class Principal extends javax.swing.JFrame {

    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrincipal = new javax.swing.JDesktopPane();
        mnuBarra = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroUsuario = new javax.swing.JMenuItem();
        mnuAdministrador = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dskPrincipal.setBackground(new java.awt.Color(60, 63, 65));
        dskPrincipal.setAutoscrolls(true);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        mnuArquivo.setMnemonic('A');
        mnuArquivo.setText("Arquivo");

        mnuCadastro.setMnemonic('c');
        mnuCadastro.setText("Vendedor");

        mnuCadastroUsuario.setMnemonic('u');
        mnuCadastroUsuario.setText("teste");
        mnuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroUsuarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroUsuario);

        mnuArquivo.add(mnuCadastro);

        mnuAdministrador.setMnemonic('a');
        mnuAdministrador.setText("Administrador");
        mnuAdministrador.setEnabled(false);
        mnuArquivo.add(mnuAdministrador);

        mnuSair.setMnemonic('r');
        mnuSair.setText("Sair");
        mnuArquivo.add(mnuSair);

        mnuBarra.add(mnuArquivo);

        mnuAjuda.setMnemonic('u');
        mnuAjuda.setText("Ajuda");
        mnuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjudaActionPerformed(evt);
            }
        });

        mnuSobre.setMnemonic('s');
        mnuSobre.setText("Sobre");
        mnuAjuda.add(mnuSobre);

        mnuBarra.add(mnuAjuda);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dskPrincipal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dskPrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroUsuarioActionPerformed
        InterfaceVendedor interVenedor = new InterfaceVendedor();
        interVenedor.setVisible(true);
        dskPrincipal.add(interVenedor);
    }//GEN-LAST:event_mnuCadastroUsuarioActionPerformed

    private void mnuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjudaActionPerformed
        // Exemplo de criação de uma nova janela na área de trabalho do programa
        //        JanelaSobre janelaSobre = new JanelaSobre();
        //        janelaSobre.setVisible(true);
        //        dskPrincipal.add(janelaSobre);
    }//GEN-LAST:event_mnuAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenuItem mnuAdministrador;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroUsuario;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSobre;
    // End of variables declaration//GEN-END:variables
}
